### ISSUE TITLE
Travis build fails to find protobufjs noparse file.

### ISSUE THREAD

**Issue by Tzrlk** [aetheric/session-persist#1]
```
Error: Cannot find module '/home/travis/build/aetheric/sockit/node_modules/protobufjs/dist/ProtoBuf.noparse.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.require.resolve (module.js:384:19)
    at /home/travis/build/aetheric/sockit/node_modules/gulp-browserify/node_modules/browserify-shim/index.js:91:34
    at Array.forEach (native)
    at shim (/home/travis/build/aetheric/sockit/node_modules/gulp-browserify/node_modules/browserify-shim/index.js:86:6)
    at Transform.transform [as _transform] (/home/travis/build/aetheric/sockit/node_modules/gulp-browserify/index.js:97:17)
    at Transform._read (/home/travis/build/aetheric/sockit/node_modules/gulp-browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/home/travis/build/aetheric/sockit/node_modules/gulp-browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/home/travis/build/aetheric/sockit/node_modules/gulp-browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/home/travis/build/aetheric/sockit/node_modules/gulp-browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
```

**Comment by Tzrlk** [comment]
I'm thinking of just not bothering. Can always optimise later.

**Comment by Tzrlk** [comment]
Issue resolved.
